apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mssupport-0
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-storage-class
  hostPath:
    path: "/data/mssupport-0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mssupport-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-storage-class
  hostPath:
    path: "/data/mssupport-1"